/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jc;

import java.util.*;
public class Jc {
static int no;
static int c;
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Random r=new Random();
        c=r.nextInt(10);
        
        Scanner s=new Scanner(System.in);
        System.out.println("Guessing Game");
        System.out.println("Enter the number that you think will be generated by the system:");
        no=s.nextInt();
        if(c>0&&c<=10&&c==no){
            System.out.println("You have successfully guessed the correct number");
        }
        else{
            System.out.println("Try again");
        }
    }
    
}
